version: "2"

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - jfrog
    volumes:
      - jfrog-artifactory:/var/opt/jfrog/artifactory
    restart: always

networks:
  jfrog:
    driver: bridge

volumes:
  jfrog-artifactory:
